server:
  port: 80

spring:
  profiles:
    # 外置jdbc和log配置文件
    active: jdbc,log

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
    encoding: UTF-8
    mode: HTML5

mybatis:
  mapper-locations: classpath:/mapper/*.xml


